export default {
  symbol: [
    { code: 'H/W/U', image: 'mana_phywu.png', 'image font size': '75' },
    { code: 'H/W/B', image: 'mana_phywb.png', 'image font size': '75' },
    { code: 'H/U/B', image: 'mana_phyub.png', 'image font size': '75' },
    { code: 'H/U/R', image: 'mana_phyur.png', 'image font size': '75' },
    { code: 'H/B/R', image: 'mana_phybr.png', 'image font size': '75' },
    { code: 'H/B/G', image: 'mana_phybg.png', 'image font size': '75' },
    { code: 'H/R/G', image: 'mana_phyrg.png', 'image font size': '75' },
    { code: 'H/R/W', image: 'mana_phyrw.png', 'image font size': '75' },
    { code: 'H/G/W', image: 'mana_phygw.png', 'image font size': '75' },
    { code: 'H/G/U', image: 'mana_phygu.png', 'image font size': '75' },
    {
      image: 'empty_loyaltyup_w.png',
      code: '([+][XYZ1-9])',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.10',
      'text margin right': '0',
      'text margin top': '.21',
      'text margin bottom': '.05',
      'text font': {
        name: 'Beleren Bold',
        size: '.70',
        color: 'white',
        'max stretch': '0.5',
      },
      'image font size': '100',
      enabled: '{white_text()}',
    },
    {
      image: 'empty_loyaltydown_w.png',
      code: '([-][XYZ1-9])',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.10',
      'text margin right': '0',
      'text margin top': '0.1',
      'text margin bottom': '.15',
      'text font': {
        name: 'Beleren Bold',
        size: '.70',
        color: 'white',
        'max stretch': '0.5',
      },
      'image font size': '100',
      enabled: '{white_text()}',
    },
    {
      image: 'empty_loyaltynaught_w.png',
      code: '[+=]([0-9XYZ])',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.10',
      'text margin right': '0',
      'text margin top': '.15',
      'text margin bottom': '.1',
      'text font': {
        name: 'Beleren Bold',
        size: '.70',
        color: 'white',
        'max stretch': '0.5',
      },
      'image font size': '100',
      enabled: '{white_text()}',
    },
    {
      image: 'empty_loyaltyup.png',
      code: '([+][XYZ1-9])',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.10',
      'text margin right': '0',
      'text margin top': '.21',
      'text margin bottom': '.05',
      'text font': {
        name: 'Beleren Bold',
        size: '.70',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '100',
    },
    {
      image: 'empty_loyaltydown.png',
      code: '([-][XYZ1-9])',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.10',
      'text margin right': '0',
      'text margin top': '0.1',
      'text margin bottom': '.15',
      'text font': {
        name: 'Beleren Bold',
        size: '.70',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '100',
    },
    {
      image: 'empty_loyaltynaught.png',
      code: '[+=]([0-9XYZ])',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.10',
      'text margin right': '0',
      'text margin top': '.15',
      'text margin bottom': '.1',
      'text font': {
        name: 'Beleren Bold',
        size: '.70',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '100',
    },
    { code: 'phi', image: 'phi.png', 'image font size': '27' },
    { code: 'E', image: 'energy.png', 'image font size': '300' },
    { code: '.5', image: 'one_half.png', 'image font size': '206' },
    { code: 'S', image: 'mana_s.png' },
    {
      code: 'T',
      image: 'mana_t_older.png',
      enabled: '{ mana_t() == "older" }',
    },
    { code: 'T', image: 'mana_t_old.png', enabled: '{ mana_t() == "old" }' },
    { code: 'T', image: 'mana_t.png' },
    {
      code: 'Q',
      image: 'mana_q_older.png',
      enabled: '{ mana_t() == "older" }',
    },
    { code: 'Q', image: 'mana_q_old.png', enabled: '{ mana_t() == "old" }' },
    { code: 'Q', image: 'mana_q.png' },
    { code: 'chaos', image: 'mana_chaos.png', 'image font size': '168.75' },
    { code: 'A', image: 'mana_chaos.png', 'image font size': '168.75' },
    { code: 'W/U/B/R/G', image: 'mana_wubrg.png' },
    { code: 'W/U/B', image: {}, 'image font size': '145' },
    { code: 'U/B/R', image: {}, 'image font size': '145' },
    { code: 'B/R/G', image: {}, 'image font size': '145' },
    { code: 'R/G/W', image: {}, 'image font size': '145' },
    { code: 'G/W/U', image: {}, 'image font size': '145' },
    { code: 'W/B/R', image: {}, 'image font size': '145' },
    { code: 'U/R/G', image: {}, 'image font size': '145' },
    { code: 'B/G/W', image: {}, 'image font size': '145' },
    { code: 'R/W/U', image: {}, 'image font size': '145' },
    { code: 'G/U/B', image: {}, 'image font size': '145' },
    {
      code: 'W/U',
      image: 'mana_guild_wu.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'U/B',
      image: 'mana_guild_ub.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'B/R',
      image: 'mana_guild_br.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'R/G',
      image: 'mana_guild_rg.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'G/W',
      image: 'mana_guild_gw.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'W/B',
      image: 'mana_guild_wb.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'U/R',
      image: 'mana_guild_ur.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'B/G',
      image: 'mana_guild_bg.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'R/W',
      image: 'mana_guild_rw.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'G/U',
      image: 'mana_guild_gu.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'W/U',
      image:
        '{ masked_blend(dark: "mana_ww.png", light: "mana_uu.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'U/B',
      image:
        '{ masked_blend(dark: "mana_uu.png", light: "mana_bb.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'B/R',
      image:
        '{ masked_blend(dark: "mana_bb.png", light: "mana_rr.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'R/G',
      image:
        '{ masked_blend(dark: "mana_rr.png", light: "mana_gg.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'G/W',
      image:
        '{ masked_blend(dark: "mana_gg.png", light: "mana_ww.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'W/B',
      image:
        '{ masked_blend(dark: "mana_ww.png", light: "mana_bb.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'U/R',
      image:
        '{ masked_blend(dark: "mana_uu.png", light: "mana_rr.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'B/G',
      image:
        '{ masked_blend(dark: "mana_bb.png", light: "mana_gg.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'R/W',
      image:
        '{ masked_blend(dark: "mana_rr.png", light: "mana_ww.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'G/U',
      image:
        '{ masked_blend(dark: "mana_gg.png", light: "mana_uu.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/W',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_ww.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/U',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_uu.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/B',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_bb.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/R',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_rr.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/G',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_gg.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'H/W',
      image:
        '{ masked_blend(light: "black_circle.png", dark: "mana_circle_w.png", mask: "mask_phyrexian.png") }',
      'image font size': '117',
    },
    {
      code: 'H/U',
      image:
        '{ masked_blend(light: "black_circle.png", dark: "mana_circle_u.png", mask: "mask_phyrexian.png") }',
      'image font size': '117',
    },
    {
      code: 'H/B',
      image:
        '{ masked_blend(light: "black_circle.png", dark: "mana_circle_b.png", mask: "mask_phyrexian.png") }',
      'image font size': '117',
    },
    {
      code: 'H/R',
      image:
        '{ masked_blend(light: "black_circle.png", dark: "mana_circle_r.png", mask: "mask_phyrexian.png") }',
      'image font size': '117',
    },
    {
      code: 'H/G',
      image:
        '{ masked_blend(light: "black_circle.png", dark: "mana_circle_g.png", mask: "mask_phyrexian.png") }',
      'image font size': '117',
    },
    {
      code: 'H',
      image:
        '{ masked_blend(light: "black_circle.png", dark: "mana_circle.png", mask: "mask_phyrexian.png") }',
      'image font size': '117',
    },
    { code: 'D/W', image: 'mana_dw.png', 'image font size': '117' },
    { code: 'D/U', image: 'mana_du.png', 'image font size': '117' },
    { code: 'D/B', image: 'mana_db.png', 'image font size': '117' },
    { code: 'D/R', image: 'mana_dr.png', 'image font size': '117' },
    { code: 'D/G', image: 'mana_dg.png', 'image font size': '117' },
    { code: 'D', image: 'mana_dc.png', 'image font size': '117' },
    { code: 'L/W', image: 'mana_loyal_w.png', 'image font size': '120' },
    { code: 'L/U', image: 'mana_loyal_u.png', 'image font size': '120' },
    { code: 'L/B', image: 'mana_loyal_b.png', 'image font size': '120' },
    { code: 'L/R', image: 'mana_loyal_r.png', 'image font size': '120' },
    { code: 'L/G', image: 'mana_loyal_g.png', 'image font size': '120' },
    { code: '2/W', image: '2W.png', enabled: '{ancestral_mana()}' },
    { code: '2/U', image: '2U.png', enabled: '{ancestral_mana()}' },
    { code: '2/B', image: '2B.png', enabled: '{ancestral_mana()}' },
    { code: '2/R', image: '2R.png', enabled: '{ancestral_mana()}' },
    { code: '2/G', image: '2G.png', enabled: '{ancestral_mana()}' },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_ww.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/W',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_uu.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/U',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_bb.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/B',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_rr.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/R',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_gg.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/G',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_pp.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/P',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_kk.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/K',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_ss.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/S',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_cc.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/C',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image: 'mana_circle.png',
      code: '[XYZ]',
      regex: 'yes',
      'draw text': '0',
      'text margin left': '.23',
      'text margin right': '.23',
      'text margin top': '-.11',
      'text margin bottom': '-.11',
      'text font': { name: 'MPlantin', size: '1', color: 'black' },
    },
    { image: 'mana_infinite.png', code: '∞' },
    { code: '100', image: '100.png' },
    { code: '99(?!/)', regex: 'yes', image: '99.png' },
    { code: '30(?!/)', regex: 'yes', image: '30.png' },
    { code: '29(?!/)', regex: 'yes', image: '29.png' },
    { code: '28(?!/)', regex: 'yes', image: '28.png' },
    { code: '27(?!/)', regex: 'yes', image: '27.png' },
    { code: '26(?!/)', regex: 'yes', image: '26.png' },
    { code: '25(?!/)', regex: 'yes', image: '25.png' },
    { code: '24(?!/)', regex: 'yes', image: '24.png' },
    { code: '23(?!/)', regex: 'yes', image: '23.png' },
    { code: '22(?!/)', regex: 'yes', image: '22.png' },
    { code: '21(?!/)', regex: 'yes', image: '21.png' },
    { code: '20(?!/)', regex: 'yes', image: '20.png' },
    { code: '19(?!/)', regex: 'yes', image: '19.png' },
    { code: '18(?!/)', regex: 'yes', image: '18.png' },
    { code: '17(?!/)', regex: 'yes', image: '17.png' },
    { code: '16(?!/)', regex: 'yes', image: '16.png' },
    { code: '15(?!/)', regex: 'yes', image: '15.png' },
    { code: '14(?!/)', regex: 'yes', image: '14.png' },
    { code: '13(?!/)', regex: 'yes', image: '13.png' },
    { code: '12(?!/)', regex: 'yes', image: '12.png' },
    { code: '11(?!/)', regex: 'yes', image: '11.png' },
    { code: '10(?!/)', regex: 'yes', image: '10.png' },
    { code: '9', image: '9.png', enabled: '{ancestral_mana()}' },
    { code: '8', image: '8.png', enabled: '{ancestral_mana()}' },
    { code: '7', image: '7.png', enabled: '{ancestral_mana()}' },
    { code: '6', image: '6.png', enabled: '{ancestral_mana()}' },
    { code: '5', image: '5.png', enabled: '{ancestral_mana()}' },
    { code: '4', image: '4.png', enabled: '{ancestral_mana()}' },
    { code: '3', image: '3.png', enabled: '{ancestral_mana()}' },
    { code: '2', image: '2.png', enabled: '{ancestral_mana()}' },
    { code: '1', image: '1.png', enabled: '{ancestral_mana()}' },
    { code: '0', image: '0.png', enabled: '{ancestral_mana()}' },
    { code: 'W', image: 'mana_w.png' },
    { code: 'U', image: 'mana_u.png' },
    { code: 'B', image: 'mana_b.png' },
    { code: 'R', image: 'mana_r.png' },
    { code: 'G', image: 'mana_g.png' },
    { code: 'C', image: 'mana_c.png' },
    {
      image: 'mana_circle.png',
      code: '[0-9]+(?!/[WUBRGSTQ2])|.',
      regex: 'yes',
      'draw text': '0',
      'text margin left': '.2',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '-.14',
      'text font': {
        name: 'MPlantin',
        size: '1',
        color: 'black',
        'max stretch': '0.57',
      },
    },
  ],
  'insert symbol menu': {
    item: [
      'T',
      'Q',
      'C',
      'E',
      { type: 'custom', name: 'colorless' },
      { type: 'line' },
      'W',
      'U',
      'B',
      'R',
      'G',
      'C',
      'S',
      'A',
      { type: 'line' },
      {
        name: 'hybrid',
        item: [
          'W/U',
          'U/B',
          'B/R',
          'R/G',
          'G/W',
          { type: 'line' },
          'W/B',
          'U/R',
          'B/G',
          'R/W',
          'G/U',
          'C/W',
          'C/U',
          'C/B',
          'C/R',
          'C/G',
        ],
        type: 'line',
      },
      {
        name: 'tri-hybrid mana',
        item: [
          'W/U/B',
          'U/B/R',
          'B/R/G',
          'R/G/W',
          'G/W/U',
          { type: 'line' },
          'W/B/R',
          'U/R/G',
          'B/G/W',
          'R/W/U',
          'G/U/B',
        ],
      },
      { name: 'phyrexian', item: ['H', 'H/W', 'H/U', 'H/B', 'H/R', 'H/G'] },
      { type: 'line' },
      {
        name: 'custom symbols',
        item: ['V', 'V/W', 'V/U', 'V/B', 'V/R', 'V/G'],
      },
      { type: 'line' },
      { name: 'prismatic', item: 'W/U/B/R/G' },
      { type: 'line' },
      {
        name: 'number hybrids',
        item: ['2/W', '2/U', '2/B', '2/R', '2/G', '2/C'],
      },
      { type: 'line' },
      {
        name: 'loyalty changes',
        item: [
          {
            name: '+N',
            item: [
              '+0 loyalty',
              '+1 loyalty',
              '+2 loyalty',
              '+3 loyalty',
              '+4 loyalty',
              '+5 loyalty',
              '+6 loyalty',
              '+7 loyalty',
              '+8 loyalty',
              '+9 loyalty',
              '+X loyalty',
            ],
          },
          {
            name: '-N',
            item: [
              '-0 loyalty',
              '-1 loyalty',
              '-2 loyalty',
              '-3 loyalty',
              '-4 loyalty',
              '-5 loyalty',
              '-6 loyalty',
              '-7 loyalty',
              '-8 loyalty',
              '-9 loyalty',
              '-X loyalty',
            ],
          },
          {
            name: '=N',
            item: [
              '0 loyalty',
              '1 loyalty',
              '2 loyalty',
              '3 loyalty',
              '4 loyalty',
              '5 loyalty',
              '6 loyalty',
              '7 loyalty',
              '8 loyalty',
              '9 loyalty',
              'X loyalty',
            ],
          },
        ],
      },
    ],
  },
};
