export default {
  'mse version': '0.3.9',
  version: '2020-02-07',
  'short name': 'popup style',
  'installer group': 'magic/Mana symbols/popup style',
  'position hint': '002',
  icon: 'mana_r.png',
  'depends on': {
    package: 'magic-mainframe-extras.mse-include',
    version: '2018-01-01',
  },
  'image font size': '135',
  'horizontal space': '2',
  symbol: [
    {
      code: 'V/W',
      image:
        '{"/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_w.png"}',
      'image font size': '120',
      enabled: '{use_large_v_mana() and use_color_v_mana()}',
    },
    {
      code: 'V/U',
      image:
        '{"/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_u.png"}',
      'image font size': '120',
      enabled: '{use_large_v_mana() and use_color_v_mana()}',
    },
    {
      code: 'V/B',
      image:
        '{"/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_b.png"}',
      'image font size': '120',
      enabled: '{use_large_v_mana() and use_color_v_mana()}',
    },
    {
      code: 'V/R',
      image:
        '{"/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_r.png"}',
      'image font size': '120',
      enabled: '{use_large_v_mana() and use_color_v_mana()}',
    },
    {
      code: 'V/G',
      image:
        '{"/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_g.png"}',
      'image font size': '120',
      enabled: '{use_large_v_mana() and use_color_v_mana()}',
    },
    {
      code: 'V/W',
      image:
        '{ masked_blend(dark: "/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_h.png", light: "mana_ww.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
      enabled: '{use_large_v_mana() and use_hybrid_v_mana()}',
    },
    {
      code: 'V/U',
      image:
        '{ masked_blend(dark: "/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_h.png", light: "mana_uu.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
      enabled: '{use_large_v_mana() and use_hybrid_v_mana()}',
    },
    {
      code: 'V/B',
      image:
        '{ masked_blend(dark: "/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_h.png", light: "mana_bb.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
      enabled: '{use_large_v_mana() and use_hybrid_v_mana()}',
    },
    {
      code: 'V/R',
      image:
        '{ masked_blend(dark: "/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_h.png", light: "mana_rr.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
      enabled: '{use_large_v_mana() and use_hybrid_v_mana()}',
    },
    {
      code: 'V/G',
      image:
        '{ masked_blend(dark: "/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + "_h.png", light: "mana_gg.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
      enabled: '{use_large_v_mana() and use_hybrid_v_mana()}',
    },
    {
      code: 'V',
      image:
        '{"/magic-mainframe-extras.mse-include/" + v_mana_loc() + "large/" + v_mana_name() + ".png"}',
      'image font size': '120',
      enabled: '{use_large_v_mana()}',
    },
    {
      code: 'T',
      image: 'mana_t_older.png',
      enabled: '{ mana_t() == "older" }',
    },
    { code: 'T', image: 'mana_t_old.png', enabled: '{ mana_t() == "old" }' },
    { code: 'T', image: 'mana_t.png' },
    {
      code: 'Q',
      image: 'mana_q_older.png',
      enabled: '{ mana_t() == "older" }',
    },
    { code: 'Q', image: 'mana_q_old.png', enabled: '{ mana_t() == "old" }' },
    { code: 'Q', image: 'mana_q.png' },
    { code: 'E', image: 'Energy.png' },
    { code: 'chaos', image: 'mana_chaos.png', 'image font size': '151.69' },
    { code: 'H/W/U', image: 'mana_phywu.png', 'image font size': '75' },
    { code: 'H/W/B', image: 'mana_phywb.png', 'image font size': '75' },
    { code: 'H/U/B', image: 'mana_phyub.png', 'image font size': '75' },
    { code: 'H/U/R', image: 'mana_phyur.png', 'image font size': '75' },
    { code: 'H/B/R', image: 'mana_phybr.png', 'image font size': '75' },
    { code: 'H/B/G', image: 'mana_phybg.png', 'image font size': '75' },
    { code: 'H/R/G', image: 'mana_phyrg.png', 'image font size': '75' },
    { code: 'H/R/W', image: 'mana_phyrw.png', 'image font size': '75' },
    { code: 'H/G/W', image: 'mana_phygw.png', 'image font size': '75' },
    { code: 'H/G/U', image: 'mana_phygu.png', 'image font size': '75' },
    { code: 'W/U/B/R/G', image: 'mana_wubrg.png' },
    { code: 'B/G/W', image: 'mana_bgw.png', 'image font size': '145' },
    { code: 'B/R/G', image: 'mana_brg.png', 'image font size': '145' },
    { code: 'G/U/B', image: 'mana_gub.png', 'image font size': '145' },
    { code: 'G/W/U', image: 'mana_gwu.png', 'image font size': '145' },
    { code: 'R/G/W', image: 'mana_rgw.png', 'image font size': '145' },
    { code: 'R/W/U', image: 'mana_rwu.png', 'image font size': '145' },
    { code: 'U/B/R', image: 'mana_ubr.png', 'image font size': '145' },
    { code: 'U/R/G', image: 'mana_urg.png', 'image font size': '145' },
    { code: 'W/B/R', image: 'mana_wbr.png', 'image font size': '145' },
    { code: 'W/U/B', image: 'mana_wub.png', 'image font size': '145' },
    {
      code: 'W/U',
      image: 'mana_guild_wu.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'U/B',
      image: 'mana_guild_ub.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'B/R',
      image: 'mana_guild_br.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'R/G',
      image: 'mana_guild_rg.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'G/W',
      image: 'mana_guild_gw.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'W/B',
      image: 'mana_guild_wb.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'U/R',
      image: 'mana_guild_ur.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'B/G',
      image: 'mana_guild_bg.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'R/W',
      image: 'mana_guild_rw.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    {
      code: 'G/U',
      image: 'mana_guild_gu.png',
      'image font size': '145',
      enabled: '{ guild_mana() }',
    },
    { code: 'W/U', image: 'mana_wu.png', 'image font size': '145' },
    { code: 'U/B', image: 'mana_ub.png', 'image font size': '145' },
    { code: 'B/R', image: 'mana_br.png', 'image font size': '145' },
    { code: 'R/G', image: 'mana_rg.png', 'image font size': '145' },
    { code: 'G/W', image: 'mana_gw.png', 'image font size': '145' },
    { code: 'W/B', image: 'mana_wb.png', 'image font size': '145' },
    { code: 'U/R', image: 'mana_ur.png', 'image font size': '145' },
    { code: 'B/G', image: 'mana_bg.png', 'image font size': '145' },
    { code: 'R/W', image: 'mana_rw.png', 'image font size': '145' },
    { code: 'G/U', image: 'mana_gu.png', 'image font size': '145' },
    { code: 'C/W', image: 'mana_cmc_cw.png', 'image font size': '145' },
    { code: 'C/U', image: 'mana_cmc_cu.png', 'image font size': '145' },
    { code: 'C/B', image: 'mana_cmc_cb.png', 'image font size': '145' },
    { code: 'C/R', image: 'mana_cmc_cr.png', 'image font size': '145' },
    { code: 'C/G', image: 'mana_cmc_cg.png', 'image font size': '145' },
    { code: 'D/W', image: 'mana_dw.png', 'image font size': '120' },
    { code: 'D/U', image: 'mana_du.png', 'image font size': '120' },
    { code: 'D/B', image: 'mana_db.png', 'image font size': '120' },
    { code: 'D/R', image: 'mana_dr.png', 'image font size': '120' },
    { code: 'D/G', image: 'mana_dg.png', 'image font size': '120' },
    { code: 'D/E', image: 'mana_de.png', 'image font size': '120' },
    { code: 'D/K', image: 'mana_dk.png', 'image font size': '120' },
    { code: 'D/P', image: 'mana_dp.png', 'image font size': '120' },
    { code: 'D/L', image: 'mana_dl.png', 'image font size': '120' },
    { code: 'D/O', image: 'mana_do.png', 'image font size': '120' },
    { code: 'D', image: 'mana_dc.png', 'image font size': '120' },
    { code: '1/2', image: 'mana_1_half.png' },
    { code: '|1', image: 'mana_1_half.png' },
    { code: '|W', image: 'mana_w_half.png' },
    { code: '|U', image: 'mana_u_half.png' },
    { code: '|B', image: 'mana_b_half.png' },
    { code: '|R', image: 'mana_r_half.png' },
    { code: '|G', image: 'mana_g_half.png' },
    { code: '|S', image: 'mana_s_half.png' },
    { code: 'A', image: 'mana_chaos.png' },
    { code: 'H/W', image: 'mana_phyw.png', 'image font size': '120' },
    { code: 'H/U', image: 'mana_phyu.png', 'image font size': '120' },
    { code: 'H/B', image: 'mana_phyb.png', 'image font size': '120' },
    { code: 'H/R', image: 'mana_phyr.png', 'image font size': '120' },
    { code: 'H/G', image: 'mana_phyg.png', 'image font size': '120' },
    { code: 'L/W', image: 'mana_loyal_w.png', 'image font size': '120' },
    { code: 'L/U', image: 'mana_loyal_u.png', 'image font size': '120' },
    { code: 'L/B', image: 'mana_loyal_b.png', 'image font size': '120' },
    { code: 'L/R', image: 'mana_loyal_r.png', 'image font size': '120' },
    { code: 'L/G', image: 'mana_loyal_g.png', 'image font size': '120' },
    { code: 'H', image: 'mana_phyc.png', 'image font size': '120' },
    { code: '2/W', image: '2W.png', enabled: '{ancestral_mana()}' },
    { code: '2/U', image: '2U.png', enabled: '{ancestral_mana()}' },
    { code: '2/B', image: '2B.png', enabled: '{ancestral_mana()}' },
    { code: '2/R', image: '2R.png', enabled: '{ancestral_mana()}' },
    { code: '2/G', image: '2G.png', enabled: '{ancestral_mana()}' },
    {
      image: 'mana_nw.png',
      code: '([XYZ0-9])/W',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.25',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.4',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'rgb(0,0,0)',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image: 'mana_nu.png',
      code: '([XYZ0-9])/U',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.25',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.4',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'rgb(0,0,0)',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image: 'mana_nb.png',
      code: '([XYZ0-9])/B',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.25',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.4',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'rgb(0,0,0)',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image: 'mana_nr.png',
      code: '([XYZ0-9])/R',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.25',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.4',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'rgb(0,0,0)',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image: 'mana_ng.png',
      code: '([XYZ0-9])/G',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.25',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.4',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'rgb(0,0,0)',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_ss.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/S',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.30',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.34',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image:
        '{ masked_blend(dark: "mana_circle_large.png", light: "mana_cc.png", mask: "mask_hybrid.png") }',
      code: '([XYZ0-9])/C',
      regex: 'yes',
      'draw text': '1',
      'text margin left': '-.25',
      'text margin right': '.2',
      'text margin top': '-.14',
      'text margin bottom': '.4',
      'text font': {
        name: 'MPlantin',
        size: '.6',
        color: 'black',
        'max stretch': '0.5',
      },
      'image font size': '145',
    },
    {
      image: 'mana_circle.png',
      code: '[XYZ]',
      regex: 'yes',
      'draw text': '0',
      'text margin left': '.23',
      'text margin right': '.21',
      'text margin top': '-.15',
      'text margin bottom': '-.06',
      'text font': {
        name: 'MPlantin',
        size: '1',
        color: 'rgb(0,0,0)',
        'max stretch': '0.9',
      },
    },
    { code: 'I', image: 'mana_infinite.png' },
    { code: '100', image: '100.png' },
    { code: '99(?!/)', regex: 'yes', image: '99.png' },
    { code: '30(?!/)', regex: 'yes', image: '30.png' },
    { code: '29(?!/)', regex: 'yes', image: '29.png' },
    { code: '28(?!/)', regex: 'yes', image: '28.png' },
    { code: '27(?!/)', regex: 'yes', image: '27.png' },
    { code: '26(?!/)', regex: 'yes', image: '26.png' },
    { code: '25(?!/)', regex: 'yes', image: '25.png' },
    { code: '24(?!/)', regex: 'yes', image: '24.png' },
    { code: '23(?!/)', regex: 'yes', image: '23.png' },
    { code: '22(?!/)', regex: 'yes', image: '22.png' },
    { code: '21(?!/)', regex: 'yes', image: '21.png' },
    { code: '20(?!/)', regex: 'yes', image: '20.png' },
    { code: '19(?!/)', regex: 'yes', image: '19.png' },
    { code: '18(?!/)', regex: 'yes', image: '18.png' },
    { code: '15(?!/)', regex: 'yes', image: '15.png' },
    { code: '16(?!/)', regex: 'yes', image: '16.png' },
    { code: '15(?!/)', regex: 'yes', image: '15.png' },
    { code: '14(?!/)', regex: 'yes', image: '14.png' },
    { code: '13(?!/)', regex: 'yes', image: '13.png' },
    { code: '12(?!/)', regex: 'yes', image: '12.png' },
    { code: '11(?!/)', regex: 'yes', image: '11.png' },
    { code: '10(?!/)', regex: 'yes', image: '10.png' },
    { code: '9', image: '9.png', enabled: '{ancestral_mana()}' },
    { code: '8', image: '8.png', enabled: '{ancestral_mana()}' },
    { code: '7', image: '7.png', enabled: '{ancestral_mana()}' },
    { code: '6', image: '6.png', enabled: '{ancestral_mana()}' },
    { code: '5', image: '5.png', enabled: '{ancestral_mana()}' },
    { code: '4', image: '4.png', enabled: '{ancestral_mana()}' },
    { code: '3', image: '3.png', enabled: '{ancestral_mana()}' },
    { code: '2', image: '2.png', enabled: '{ancestral_mana()}' },
    { code: '1', image: '1.png', enabled: '{ancestral_mana()}' },
    { code: '0', image: '0.png', enabled: '{ancestral_mana()}' },
    { code: 'W', image: 'mana_w.png' },
    { code: 'U', image: 'mana_u.png' },
    { code: 'B', image: 'mana_b.png' },
    { code: 'R', image: 'mana_r.png' },
    { code: 'G', image: 'mana_g.png' },
    { code: 'C', image: 'mana_c.png' },
    { code: 'S', image: 'mana_s.png' },
    {
      image: 'mana_circle.png',
      'text margin left': '.23',
      'text margin right': '.21',
      'text margin top': '-.15',
      'text margin bottom': '-.06',
      code: '[0-9](?!/[WUBRGCSTQ2])|.',
      regex: 'yes',
      'draw text': '0',
      'text font': {
        name: 'MPlantin',
        size: '1',
        color: 'rgb(0,0,0)',
        'max stretch': '0.60',
      },
    },
    {
      code: 'C/W',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_ww.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/U',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_uu.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/B',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_bb.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/R',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_rr.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
    {
      code: 'C/G',
      image:
        '{ masked_blend(dark: "mana_cc.png", light: "mana_gg.png", mask: "mask_hybrid.png") }',
      'image font size': '145',
    },
  ],
  'insert symbol menu': {
    item: [
      'T',
      'Q',
      'chaos',
      { type: 'line' },
      'X',
      'Y',
      'Z',
      'I',
      'C',
      { type: 'custom', name: 'generic' },
      { type: 'line' },
      'W',
      'U',
      'B',
      'R',
      'G',
      'S',
      { type: 'line' },
      { name: 'half', item: ['1/2', '|W', '|U', '|B', '|R', '|G', '|S'] },
      {
        name: 'hybrid',
        item: [
          'W/U',
          'U/B',
          'B/R',
          'R/G',
          'G/W',
          { type: 'line' },
          'W/B',
          'U/R',
          'B/G',
          'R/W',
          'G/U',
        ],
      },
      { name: 'colorless hybrid', item: ['C/W', 'C/U', 'C/B', 'C/R', 'C/G'] },
      { name: 'phyrexian', item: ['H', 'H/W', 'H/U', 'H/B', 'H/R', 'H/G'] },
      {
        name: 'hybrid 3',
        item: [
          'W/U/B',
          'U/B/R',
          'B/R/G',
          'R/G/W',
          'G/W/U',
          { type: 'line' },
          'W/B/R',
          'U/R/G',
          'B/G/W',
          'R/W/U',
          'G/U/B',
        ],
      },
      { type: 'line' },
      {
        name: 'number hybrids',
        item: ['2/W', '2/U', '2/B', '2/R', '2/G', '2/C'],
      },
    ],
  },
};
